# Generated by Django 6.1 on 2026-08-06 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('default_days_per_year', models.PositiveIntegerField(default=0, help_text='Allocation granted to a worker each year by default.', verbose_name='default days per year')),
                ('requires_document', models.BooleanField(default=False, help_text='Sick leave, for example, may require a medical note.', verbose_name='requires supporting document')),
                ('is_paid', models.BooleanField(default=True, verbose_name='paid leave')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'leave type',
                'verbose_name_plural': 'leave types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('reason', models.TextField(verbose_name='reason')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('review_notes', models.TextField(blank=True, verbose_name='internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
                ('supporting_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests', to='documents.workerdocument', verbose_name='supporting document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='leave.leavetype', verbose_name='leave type')),
            ],
            options={
                'verbose_name': 'leave request',
                'verbose_name_plural': 'leave requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='leave_leave_user_id_70fd16_idx'), models.Index(fields=['status', 'start_date'], name='leave_leave_status_787f14_idx'), models.Index(fields=['start_date', 'end_date'], name='leave_leave_start_d_611c6f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='leave_end_date_after_start_date')],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='year')),
                ('days_allocated', models.PositiveIntegerField(default=0, verbose_name='days allocated')),
                ('days_used', models.PositiveIntegerField(default=0, verbose_name='days used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='leave.leavetype', verbose_name='leave type')),
            ],
            options={
                'verbose_name': 'leave balance',
                'verbose_name_plural': 'leave balances',
                'ordering': ['-year', 'leave_type__name'],
                'indexes': [models.Index(fields=['user', 'year'], name='leave_leave_user_id_029202_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'leave_type', 'year'), name='unique_leave_balance_per_user_type_year')],
            },
        ),
    ]
