# Generated by Django 6.1 on 2026-08-07 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentDailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_present', models.PositiveIntegerField(default=0, verbose_name='days present')),
                ('days_late', models.PositiveIntegerField(default=0, verbose_name='days late')),
                ('days_absent', models.PositiveIntegerField(default=0, verbose_name='days absent')),
                ('days_on_leave', models.PositiveIntegerField(default=0, verbose_name='days on leave')),
                ('days_flagged', models.PositiveIntegerField(default=0, verbose_name='days flagged')),
                ('generated_at', models.DateTimeField(auto_now=True, verbose_name='generated at')),
                ('date', models.DateField(verbose_name='date')),
                ('headcount', models.PositiveIntegerField(default=0, help_text='Approved, active workers in the department on this date.', verbose_name='headcount')),
                ('flagged_attempts', models.PositiveIntegerField(default=0, help_text='Failed GPS/face/liveness checks awaiting review.', verbose_name='flagged verification attempts')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='organisations.department', verbose_name='department')),
            ],
            options={
                'verbose_name': 'department daily summary',
                'verbose_name_plural': 'department daily summaries',
                'ordering': ['-date'],
                'abstract': False,
                'indexes': [models.Index(fields=['department', '-date'], name='analytics_d_departm_55075d_idx'), models.Index(fields=['-date'], name='analytics_d_date_49ca3a_idx')],
                'constraints': [models.UniqueConstraint(fields=('department', 'date'), name='unique_department_daily_summary')],
            },
        ),
        migrations.CreateModel(
            name='WorkerDailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_present', models.PositiveIntegerField(default=0, verbose_name='days present')),
                ('days_late', models.PositiveIntegerField(default=0, verbose_name='days late')),
                ('days_absent', models.PositiveIntegerField(default=0, verbose_name='days absent')),
                ('days_on_leave', models.PositiveIntegerField(default=0, verbose_name='days on leave')),
                ('days_flagged', models.PositiveIntegerField(default=0, verbose_name='days flagged')),
                ('generated_at', models.DateTimeField(auto_now=True, verbose_name='generated at')),
                ('date', models.DateField(verbose_name='date')),
                ('minutes_late', models.PositiveIntegerField(default=0, verbose_name='minutes late')),
                ('minutes_worked', models.PositiveIntegerField(default=0, verbose_name='minutes worked')),
                ('department', models.ForeignKey(blank=True, help_text='Copied in at roll-up time so later transfers do not rewrite history.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_daily_summaries', to='organisations.department', verbose_name='department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'worker daily summary',
                'verbose_name_plural': 'worker daily summaries',
                'ordering': ['-date'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', '-date'], name='analytics_w_user_id_3b6817_idx'), models.Index(fields=['department', '-date'], name='analytics_w_departm_a5523c_idx'), models.Index(fields=['-date'], name='analytics_w_date_27cfa8_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_worker_daily_summary')],
            },
        ),
        migrations.CreateModel(
            name='WorkerMonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_present', models.PositiveIntegerField(default=0, verbose_name='days present')),
                ('days_late', models.PositiveIntegerField(default=0, verbose_name='days late')),
                ('days_absent', models.PositiveIntegerField(default=0, verbose_name='days absent')),
                ('days_on_leave', models.PositiveIntegerField(default=0, verbose_name='days on leave')),
                ('days_flagged', models.PositiveIntegerField(default=0, verbose_name='days flagged')),
                ('generated_at', models.DateTimeField(auto_now=True, verbose_name='generated at')),
                ('year', models.PositiveIntegerField(verbose_name='year')),
                ('month', models.PositiveSmallIntegerField(help_text='1-12', verbose_name='month')),
                ('total_minutes_late', models.PositiveIntegerField(default=0, verbose_name='total minutes late')),
                ('total_minutes_worked', models.PositiveIntegerField(default=0, verbose_name='total minutes worked')),
                ('leave_days_used', models.PositiveIntegerField(default=0, verbose_name='leave days used')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_monthly_summaries', to='organisations.department', verbose_name='department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'worker monthly summary',
                'verbose_name_plural': 'worker monthly summaries',
                'ordering': ['-year', '-month'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', '-year', '-month'], name='analytics_w_user_id_f1aa73_idx'), models.Index(fields=['department', '-year', '-month'], name='analytics_w_departm_e6cbe7_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'year', 'month'), name='unique_worker_monthly_summary')],
            },
        ),
    ]
