# Generated by Django 6.1 on 2026-08-06 21:56

import accounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone number')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('employee_id', models.CharField(blank=True, help_text='Optional payroll or HR reference for this worker.', max_length=50, verbose_name='employee ID')),
                ('role', models.CharField(choices=[('worker', 'Worker'), ('dept_manager', 'Department Manager'), ('admin', 'Administrator')], default='worker', max_length=20, verbose_name='role')),
                ('is_approved', models.BooleanField(default=False, help_text='An administrator has approved this account for attendance.', verbose_name='approved')),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='active', max_length=20, verbose_name='employment status')),
                ('biometric_consent_at', models.DateTimeField(blank=True, help_text='When the user explicitly consented to face data being stored.', null=True, verbose_name='biometric consent given at')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['email'],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
