# Generated by Django 6.1 on 2026-08-07 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('account_registered', 'Account Registered'), ('account_approved', 'Account Approved'), ('account_rejected', 'Account Rejected'), ('account_suspended', 'Account Suspended'), ('face_enrolled', 'Face Enrolled'), ('face_re_enrolled', 'Face Re-enrolled'), ('face_data_deleted', 'Face Data Deleted'), ('consent_given', 'Biometric Consent Given'), ('consent_withdrawn', 'Biometric Consent Withdrawn'), ('check_in', 'Check-in Recorded'), ('check_out', 'Check-out Recorded'), ('check_in_rejected', 'Check-in Rejected'), ('attendance_overridden', 'Attendance Manually Overridden'), ('leave_requested', 'Leave Requested'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('leave_cancelled', 'Leave Cancelled'), ('document_uploaded', 'Document Uploaded'), ('document_verified', 'Document Verified'), ('document_rejected', 'Document Rejected'), ('location_created', 'Work Location Created'), ('location_updated', 'Work Location Updated'), ('threshold_changed', 'Verification Threshold Changed'), ('other', 'Other')], max_length=40, verbose_name='action')),
                ('target_app', models.CharField(blank=True, max_length=50, verbose_name='target app')),
                ('target_model', models.CharField(blank=True, max_length=50, verbose_name='target model')),
                ('target_id', models.CharField(blank=True, max_length=50, verbose_name='target id')),
                ('description', models.TextField(blank=True, help_text='Human-readable summary shown in the admin audit view.', verbose_name='description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Scores, thresholds, before/after values — whatever explains the decision.', verbose_name='metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='user agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('actor', models.ForeignKey(blank=True, help_text='Who performed the action; empty for automated system actions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions_performed', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('subject', models.ForeignKey(blank=True, help_text='The worker the action concerns.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions_received', to=settings.AUTH_USER_MODEL, verbose_name='subject')),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_audit_timesta_901180_idx'), models.Index(fields=['action', '-timestamp'], name='audit_audit_action_e33994_idx'), models.Index(fields=['subject', '-timestamp'], name='audit_audit_subject_81f1e3_idx'), models.Index(fields=['actor', '-timestamp'], name='audit_audit_actor_i_dcd783_idx'), models.Index(fields=['target_app', 'target_model', 'target_id'], name='audit_audit_target__a4b646_idx')],
            },
        ),
    ]
