# Generated by Django 6.1 on 2026-08-06 21:56

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_card', 'Identification Card'), ('certification', 'Certification'), ('contract', 'Contract'), ('medical_note', 'Medical Note'), ('other', 'Other')], default='other', max_length=20, verbose_name='document type')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('file', models.FileField(help_text='Stored under MEDIA_ROOT; move to encrypted object storage in production.', upload_to=documents.models.document_upload_path, verbose_name='file')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='original filename')),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='file size (bytes)')),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending_review', max_length=20, verbose_name='status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='issue date')),
                ('expiry_date', models.DateField(blank=True, help_text='Set for renewable documents so reminders can be sent.', null=True, verbose_name='expiry date')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'worker document',
                'verbose_name_plural': 'worker documents',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user', '-uploaded_at'], name='documents_w_user_id_1bdc1f_idx'), models.Index(fields=['status', 'document_type'], name='documents_w_status_cc84d7_idx'), models.Index(fields=['expiry_date'], name='documents_w_expiry__76b8e6_idx')],
            },
        ),
    ]
