# Generated by Django 6.1 on 2026-08-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'document_type',
                    models.CharField(
                        choices=[
                            ('id_card', 'Identification Card'),
                            ('certification', 'Certification'),
                            ('contract', 'Contract'),
                            ('medical_note', 'Medical Note'),
                            ('other', 'Other'),
                        ],
                        default='other',
                        max_length=20,
                        verbose_name='document type',
                    ),
                ),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('instructions', models.TextField(blank=True, verbose_name='instructions')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='due date')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Awaiting Upload'),
                            ('submitted', 'Submitted for Review'),
                            ('completed', 'Completed'),
                            ('cancelled', 'Cancelled'),
                        ],
                        default='pending',
                        max_length=20,
                        verbose_name='status',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='issued_document_requests',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='requested by',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='document_requests',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='worker',
                    ),
                ),
            ],
            options={
                'verbose_name': 'document request',
                'verbose_name_plural': 'document requests',
                'ordering': ['status', 'due_date', '-created_at'],
                'indexes': [
                    models.Index(fields=['user', 'status'], name='documents_d_user_id_5717c9_idx'),
                    models.Index(fields=['due_date'], name='documents_d_due_dat_784698_idx'),
                ],
            },
        ),
        migrations.AddField(
            model_name='workerdocument',
            name='request',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='submissions',
                to='documents.documentrequest',
                verbose_name='document request',
            ),
        ),
    ]
