# Generated by Django 6.0.8 on 2026-08-14

import django.db.models.deletion
from django.db import migrations, models


def move_requests_to_departments(apps, schema_editor):
    DocumentRequest = apps.get_model('documents', 'DocumentRequest')
    User = apps.get_model('accounts', 'User')

    department_by_user = dict(
        User.objects.filter(department_id__isnull=False).values_list(
            'id',
            'department_id',
        )
    )
    for document_request in DocumentRequest.objects.all().iterator():
        department_id = department_by_user.get(document_request.user_id)
        if department_id is not None:
            document_request.department_id = department_id
            document_request.save(update_fields=['department'])

    DocumentRequest.objects.filter(
        status__in=['pending', 'submitted'],
    ).update(status='active')
    DocumentRequest.objects.filter(status='completed').update(status='closed')


def move_requests_back_to_users(apps, schema_editor):
    DocumentRequest = apps.get_model('documents', 'DocumentRequest')
    User = apps.get_model('accounts', 'User')

    first_user_by_department = {}
    for user_id, department_id in User.objects.filter(
        department_id__isnull=False
    ).values_list('id', 'department_id'):
        first_user_by_department.setdefault(department_id, user_id)

    for document_request in DocumentRequest.objects.all().iterator():
        document_request.user_id = first_user_by_department.get(
            document_request.department_id
        )
        document_request.save(update_fields=['user'])

    DocumentRequest.objects.filter(status='active').update(status='pending')
    DocumentRequest.objects.filter(status='closed').update(status='completed')


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentrequest_workerdocument_request'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='department',
            field=models.ForeignKey(
                help_text=(
                    'Every employee currently assigned to this department will '
                    'see the request.'
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='document_requests',
                to='organisations.department',
                verbose_name='department',
            ),
        ),
        migrations.RunPython(
            move_requests_to_departments,
            move_requests_back_to_users,
        ),
        migrations.RemoveIndex(
            model_name='documentrequest',
            name='documents_d_user_id_5717c9_idx',
        ),
        migrations.RemoveField(
            model_name='documentrequest',
            name='user',
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='status',
            field=models.CharField(
                choices=[
                    ('active', 'Active'),
                    ('closed', 'Closed'),
                    ('cancelled', 'Cancelled'),
                ],
                default='active',
                max_length=20,
                verbose_name='status',
            ),
        ),
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(
                fields=['department', 'status'],
                name='documents_req_dept_status_idx',
            ),
        ),
    ]
