# Generated by Django 6.0.8 on 2026-08-15 13:52

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_department_document_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdocument',
            name='file',
            field=models.FileField(help_text='Stored privately; access is provided with a short-lived signed URL.', upload_to=documents.models.document_upload_path, verbose_name='file'),
        ),
    ]
