# Generated by Django 6.1 on 2026-08-06 21:56

import django.db.models.deletion
import enrollment.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField(help_text='ArcFace vector averaged over the enrolment frames.', validators=[enrollment.models.validate_embedding], verbose_name='face embedding')),
                ('embedding_dim', models.PositiveIntegerField(default=512, verbose_name='embedding dimensions')),
                ('model_version', models.CharField(blank=True, help_text='Which ArcFace model produced this embedding, for re-enrolment tracking.', max_length=100, verbose_name='model version')),
                ('liveness_score', models.FloatField(default=0.0, help_text='Anti-spoofing confidence recorded at enrolment (0-1).', verbose_name='liveness score')),
                ('frames_captured', models.PositiveIntegerField(default=0, help_text='How many good frames were averaged into the embedding.', verbose_name='frames captured')),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='enrollment/reference/%Y/%m/', verbose_name='reference image')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='enrolled at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'face profile',
                'verbose_name_plural': 'face profiles',
                'ordering': ['-enrolled_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='enrollment__user_id_fd477b_idx')],
            },
        ),
    ]
