# Generated by Django 6.1 on 2026-08-06 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('rejection_reason', models.TextField(blank=True, help_text='Shown to the worker so they know what to correct.', verbose_name='rejection reason')),
                ('review_notes', models.TextField(blank=True, help_text='Visible to administrators only.', verbose_name='internal notes')),
                ('submission_count', models.PositiveIntegerField(default=1, help_text='Increases each time a rejected worker re-submits.', verbose_name='submission count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_approval_requests', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'account approval request',
                'verbose_name_plural': 'account approval requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='approvals_a_status_2751b6_idx'), models.Index(fields=['user', 'status'], name='approvals_a_user_id_4f04e5_idx')],
            },
        ),
    ]
