# Generated by Django 6.1 on 2026-08-07 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, unique=True, verbose_name='push token')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=10, verbose_name='platform')),
                ('device_name', models.CharField(blank=True, max_length=255, verbose_name='device name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'device token',
                'verbose_name_plural': 'device tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='notificatio_user_id_f0e72c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('account_approved', 'Account Approved'), ('account_rejected', 'Account Rejected'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('leave_request_pending', 'Leave Request Awaiting Review'), ('document_verified', 'Document Verified'), ('document_rejected', 'Document Rejected'), ('document_expiring', 'Document Expiring Soon'), ('late_sign_in', 'Late Sign-in'), ('missing_check_out', 'Missing Check-out'), ('verification_flagged', 'Verification Attempt Flagged'), ('enrollment_required', 'Face Enrolment Required'), ('general', 'General')], default='general', max_length=30, verbose_name='type')),
                ('channel', models.CharField(choices=[('push', 'Push Notification'), ('email', 'Email'), ('in_app', 'In-app Only')], default='push', max_length=10, verbose_name='channel')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Extra data for the client, e.g. the leave request id to deep-link to.', verbose_name='payload')),
                ('target_app', models.CharField(blank=True, max_length=50, verbose_name='target app')),
                ('target_model', models.CharField(blank=True, max_length=50, verbose_name='target model')),
                ('target_id', models.CharField(blank=True, max_length=50, verbose_name='target id')),
                ('is_read', models.BooleanField(default=False, verbose_name='read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10, verbose_name='delivery status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('delivery_error', models.TextField(blank=True, verbose_name='delivery error')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='retry count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['delivery_status', '-created_at'], name='notificatio_deliver_460f74_idx')],
            },
        ),
    ]
