# Generated by Django 6.1 on 2026-08-06 21:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(verbose_name='check-in time')),
                ('check_in_latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='check-in latitude')),
                ('check_in_longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='check-in longitude')),
                ('check_in_distance_meters', models.FloatField(blank=True, null=True, verbose_name='check-in distance from site (metres)')),
                ('check_in_face_score', models.FloatField(blank=True, null=True, verbose_name='check-in face similarity')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='check-out time')),
                ('check_out_latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='check-out latitude')),
                ('check_out_longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='check-out longitude')),
                ('check_out_distance_meters', models.FloatField(blank=True, null=True, verbose_name='check-out distance from site (metres)')),
                ('check_out_face_score', models.FloatField(blank=True, null=True, verbose_name='check-out face similarity')),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('on_leave', 'On Leave'), ('absent', 'Absent'), ('flagged', 'Flagged for Review'), ('rejected', 'Rejected')], default='present', max_length=20, verbose_name='status')),
                ('minutes_late', models.PositiveIntegerField(default=0, verbose_name='minutes late')),
                ('is_manual_override', models.BooleanField(default=False, verbose_name='manual override')),
                ('override_reason', models.TextField(blank=True, verbose_name='override reason')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='overridden by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('work_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='organisations.worklocation', verbose_name='work location')),
            ],
            options={
                'verbose_name': 'attendance record',
                'verbose_name_plural': 'attendance records',
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='VerificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_type', models.CharField(choices=[('gps', 'GPS Geofence'), ('liveness', 'Liveness / Anti-spoofing'), ('face', 'Face Match')], max_length=20, verbose_name='attempt type')),
                ('result', models.BooleanField(default=False, verbose_name='passed')),
                ('score', models.FloatField(blank=True, help_text='Similarity, liveness confidence, or distance in metres.', null=True, verbose_name='score')),
                ('threshold_used', models.FloatField(blank=True, help_text='The value the score was compared against at the time.', null=True, verbose_name='threshold used')),
                ('reason_failed', models.TextField(blank=True, verbose_name='reason failed')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('device_info', models.CharField(blank=True, max_length=255, verbose_name='device info')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('attendance_record', models.ForeignKey(blank=True, help_text='Empty when the attempt failed before a record was created.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_attempts', to='attendance.attendancerecord', verbose_name='attendance record')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_attempts', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('work_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_attempts', to='organisations.worklocation', verbose_name='work location')),
            ],
            options={
                'verbose_name': 'verification attempt',
                'verbose_name_plural': 'verification attempts',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['user', '-check_in_time'], name='attendance__user_id_3926a6_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['work_location', '-check_in_time'], name='attendance__work_lo_db9068_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['status'], name='attendance__status_741eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationattempt',
            index=models.Index(fields=['user', '-timestamp'], name='attendance__user_id_83e9ed_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationattempt',
            index=models.Index(fields=['attempt_type', 'result'], name='attendance__attempt_bac870_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationattempt',
            index=models.Index(fields=['-timestamp'], name='attendance__timesta_06a9aa_idx'),
        ),
    ]
